// Copyright (c) 2024 turtacn
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: vcluster/api/v1/vcluster_api.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VClusterService_CreateVCluster_FullMethodName        = "/vcluster.api.v1.VClusterService/CreateVCluster"
	VClusterService_GetVCluster_FullMethodName           = "/vcluster.api.v1.VClusterService/GetVCluster"
	VClusterService_ListVClusters_FullMethodName         = "/vcluster.api.v1.VClusterService/ListVClusters"
	VClusterService_UpdateVCluster_FullMethodName        = "/vcluster.api.v1.VClusterService/UpdateVCluster"
	VClusterService_DeleteVCluster_FullMethodName        = "/vcluster.api.v1.VClusterService/DeleteVCluster"
	VClusterService_ScaleVCluster_FullMethodName         = "/vcluster.api.v1.VClusterService/ScaleVCluster"
	VClusterService_SuspendVCluster_FullMethodName       = "/vcluster.api.v1.VClusterService/SuspendVCluster"
	VClusterService_ResumeVCluster_FullMethodName        = "/vcluster.api.v1.VClusterService/ResumeVCluster"
	VClusterService_SnapshotVCluster_FullMethodName      = "/vcluster.api.v1.VClusterService/SnapshotVCluster"
	VClusterService_RestoreVCluster_FullMethodName       = "/vcluster.api.v1.VClusterService/RestoreVCluster"
	VClusterService_GetVClusterKubeconfig_FullMethodName = "/vcluster.api.v1.VClusterService/GetVClusterKubeconfig"
	VClusterService_WatchVCluster_FullMethodName         = "/vcluster.api.v1.VClusterService/WatchVCluster"
)

// VClusterServiceClient is the client API for VClusterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VClusterService provides VM-like APIs for managing virtual Kubernetes clusters.
// This service abstracts vcluster operations into familiar IaaS-style semantics
// while preserving vcluster's cloud-native characteristics.
type VClusterServiceClient interface {
	// CreateVCluster creates a new virtual Kubernetes cluster.
	// Similar to VM provisioning, but creates a vcluster control plane.
	CreateVCluster(ctx context.Context, in *CreateVClusterRequest, opts ...grpc.CallOption) (*CreateVClusterResponse, error)
	// GetVCluster retrieves details of a specific virtual cluster.
	GetVCluster(ctx context.Context, in *GetVClusterRequest, opts ...grpc.CallOption) (*GetVClusterResponse, error)
	// ListVClusters lists all virtual clusters with pagination support.
	ListVClusters(ctx context.Context, in *ListVClustersRequest, opts ...grpc.CallOption) (*ListVClustersResponse, error)
	// UpdateVCluster updates an existing virtual cluster's configuration.
	UpdateVCluster(ctx context.Context, in *UpdateVClusterRequest, opts ...grpc.CallOption) (*UpdateVClusterResponse, error)
	// DeleteVCluster deletes a virtual cluster and all its resources.
	DeleteVCluster(ctx context.Context, in *DeleteVClusterRequest, opts ...grpc.CallOption) (*DeleteVClusterResponse, error)
	// ScaleVCluster adjusts the resource allocation of a virtual cluster.
	// Similar to VM resizing, but modifies resource quotas and control-plane specs.
	ScaleVCluster(ctx context.Context, in *ScaleVClusterRequest, opts ...grpc.CallOption) (*ScaleVClusterResponse, error)
	// SuspendVCluster suspends a running virtual cluster.
	// Unlike VM power-off, this scales down control-plane pods and optionally drains workloads.
	SuspendVCluster(ctx context.Context, in *SuspendVClusterRequest, opts ...grpc.CallOption) (*SuspendVClusterResponse, error)
	// ResumeVCluster resumes a suspended virtual cluster.
	// Restores control-plane pods and reconciles workload state.
	ResumeVCluster(ctx context.Context, in *ResumeVClusterRequest, opts ...grpc.CallOption) (*ResumeVClusterResponse, error)
	// SnapshotVCluster creates a point-in-time snapshot of a virtual cluster.
	// Captures etcd state and metadata, not disk images like VM snapshots.
	SnapshotVCluster(ctx context.Context, in *SnapshotVClusterRequest, opts ...grpc.CallOption) (*SnapshotVClusterResponse, error)
	// RestoreVCluster restores a virtual cluster from a snapshot.
	RestoreVCluster(ctx context.Context, in *RestoreVClusterRequest, opts ...grpc.CallOption) (*RestoreVClusterResponse, error)
	// GetVClusterKubeconfig retrieves the kubeconfig for accessing a virtual cluster.
	GetVClusterKubeconfig(ctx context.Context, in *GetVClusterKubeconfigRequest, opts ...grpc.CallOption) (*GetVClusterKubeconfigResponse, error)
	// WatchVCluster streams real-time updates for a virtual cluster.
	WatchVCluster(ctx context.Context, in *WatchVClusterRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchVClusterResponse], error)
}

type vClusterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVClusterServiceClient(cc grpc.ClientConnInterface) VClusterServiceClient {
	return &vClusterServiceClient{cc}
}

func (c *vClusterServiceClient) CreateVCluster(ctx context.Context, in *CreateVClusterRequest, opts ...grpc.CallOption) (*CreateVClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVClusterResponse)
	err := c.cc.Invoke(ctx, VClusterService_CreateVCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vClusterServiceClient) GetVCluster(ctx context.Context, in *GetVClusterRequest, opts ...grpc.CallOption) (*GetVClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVClusterResponse)
	err := c.cc.Invoke(ctx, VClusterService_GetVCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vClusterServiceClient) ListVClusters(ctx context.Context, in *ListVClustersRequest, opts ...grpc.CallOption) (*ListVClustersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVClustersResponse)
	err := c.cc.Invoke(ctx, VClusterService_ListVClusters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vClusterServiceClient) UpdateVCluster(ctx context.Context, in *UpdateVClusterRequest, opts ...grpc.CallOption) (*UpdateVClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateVClusterResponse)
	err := c.cc.Invoke(ctx, VClusterService_UpdateVCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vClusterServiceClient) DeleteVCluster(ctx context.Context, in *DeleteVClusterRequest, opts ...grpc.CallOption) (*DeleteVClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVClusterResponse)
	err := c.cc.Invoke(ctx, VClusterService_DeleteVCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vClusterServiceClient) ScaleVCluster(ctx context.Context, in *ScaleVClusterRequest, opts ...grpc.CallOption) (*ScaleVClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScaleVClusterResponse)
	err := c.cc.Invoke(ctx, VClusterService_ScaleVCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vClusterServiceClient) SuspendVCluster(ctx context.Context, in *SuspendVClusterRequest, opts ...grpc.CallOption) (*SuspendVClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuspendVClusterResponse)
	err := c.cc.Invoke(ctx, VClusterService_SuspendVCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vClusterServiceClient) ResumeVCluster(ctx context.Context, in *ResumeVClusterRequest, opts ...grpc.CallOption) (*ResumeVClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeVClusterResponse)
	err := c.cc.Invoke(ctx, VClusterService_ResumeVCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vClusterServiceClient) SnapshotVCluster(ctx context.Context, in *SnapshotVClusterRequest, opts ...grpc.CallOption) (*SnapshotVClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotVClusterResponse)
	err := c.cc.Invoke(ctx, VClusterService_SnapshotVCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vClusterServiceClient) RestoreVCluster(ctx context.Context, in *RestoreVClusterRequest, opts ...grpc.CallOption) (*RestoreVClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreVClusterResponse)
	err := c.cc.Invoke(ctx, VClusterService_RestoreVCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vClusterServiceClient) GetVClusterKubeconfig(ctx context.Context, in *GetVClusterKubeconfigRequest, opts ...grpc.CallOption) (*GetVClusterKubeconfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVClusterKubeconfigResponse)
	err := c.cc.Invoke(ctx, VClusterService_GetVClusterKubeconfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vClusterServiceClient) WatchVCluster(ctx context.Context, in *WatchVClusterRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchVClusterResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VClusterService_ServiceDesc.Streams[0], VClusterService_WatchVCluster_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchVClusterRequest, WatchVClusterResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VClusterService_WatchVClusterClient = grpc.ServerStreamingClient[WatchVClusterResponse]

// VClusterServiceServer is the server API for VClusterService service.
// All implementations must embed UnimplementedVClusterServiceServer
// for forward compatibility.
//
// VClusterService provides VM-like APIs for managing virtual Kubernetes clusters.
// This service abstracts vcluster operations into familiar IaaS-style semantics
// while preserving vcluster's cloud-native characteristics.
type VClusterServiceServer interface {
	// CreateVCluster creates a new virtual Kubernetes cluster.
	// Similar to VM provisioning, but creates a vcluster control plane.
	CreateVCluster(context.Context, *CreateVClusterRequest) (*CreateVClusterResponse, error)
	// GetVCluster retrieves details of a specific virtual cluster.
	GetVCluster(context.Context, *GetVClusterRequest) (*GetVClusterResponse, error)
	// ListVClusters lists all virtual clusters with pagination support.
	ListVClusters(context.Context, *ListVClustersRequest) (*ListVClustersResponse, error)
	// UpdateVCluster updates an existing virtual cluster's configuration.
	UpdateVCluster(context.Context, *UpdateVClusterRequest) (*UpdateVClusterResponse, error)
	// DeleteVCluster deletes a virtual cluster and all its resources.
	DeleteVCluster(context.Context, *DeleteVClusterRequest) (*DeleteVClusterResponse, error)
	// ScaleVCluster adjusts the resource allocation of a virtual cluster.
	// Similar to VM resizing, but modifies resource quotas and control-plane specs.
	ScaleVCluster(context.Context, *ScaleVClusterRequest) (*ScaleVClusterResponse, error)
	// SuspendVCluster suspends a running virtual cluster.
	// Unlike VM power-off, this scales down control-plane pods and optionally drains workloads.
	SuspendVCluster(context.Context, *SuspendVClusterRequest) (*SuspendVClusterResponse, error)
	// ResumeVCluster resumes a suspended virtual cluster.
	// Restores control-plane pods and reconciles workload state.
	ResumeVCluster(context.Context, *ResumeVClusterRequest) (*ResumeVClusterResponse, error)
	// SnapshotVCluster creates a point-in-time snapshot of a virtual cluster.
	// Captures etcd state and metadata, not disk images like VM snapshots.
	SnapshotVCluster(context.Context, *SnapshotVClusterRequest) (*SnapshotVClusterResponse, error)
	// RestoreVCluster restores a virtual cluster from a snapshot.
	RestoreVCluster(context.Context, *RestoreVClusterRequest) (*RestoreVClusterResponse, error)
	// GetVClusterKubeconfig retrieves the kubeconfig for accessing a virtual cluster.
	GetVClusterKubeconfig(context.Context, *GetVClusterKubeconfigRequest) (*GetVClusterKubeconfigResponse, error)
	// WatchVCluster streams real-time updates for a virtual cluster.
	WatchVCluster(*WatchVClusterRequest, grpc.ServerStreamingServer[WatchVClusterResponse]) error
	mustEmbedUnimplementedVClusterServiceServer()
}

// UnimplementedVClusterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVClusterServiceServer struct{}

func (UnimplementedVClusterServiceServer) CreateVCluster(context.Context, *CreateVClusterRequest) (*CreateVClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVCluster not implemented")
}
func (UnimplementedVClusterServiceServer) GetVCluster(context.Context, *GetVClusterRequest) (*GetVClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVCluster not implemented")
}
func (UnimplementedVClusterServiceServer) ListVClusters(context.Context, *ListVClustersRequest) (*ListVClustersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVClusters not implemented")
}
func (UnimplementedVClusterServiceServer) UpdateVCluster(context.Context, *UpdateVClusterRequest) (*UpdateVClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateVCluster not implemented")
}
func (UnimplementedVClusterServiceServer) DeleteVCluster(context.Context, *DeleteVClusterRequest) (*DeleteVClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVCluster not implemented")
}
func (UnimplementedVClusterServiceServer) ScaleVCluster(context.Context, *ScaleVClusterRequest) (*ScaleVClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScaleVCluster not implemented")
}
func (UnimplementedVClusterServiceServer) SuspendVCluster(context.Context, *SuspendVClusterRequest) (*SuspendVClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SuspendVCluster not implemented")
}
func (UnimplementedVClusterServiceServer) ResumeVCluster(context.Context, *ResumeVClusterRequest) (*ResumeVClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeVCluster not implemented")
}
func (UnimplementedVClusterServiceServer) SnapshotVCluster(context.Context, *SnapshotVClusterRequest) (*SnapshotVClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SnapshotVCluster not implemented")
}
func (UnimplementedVClusterServiceServer) RestoreVCluster(context.Context, *RestoreVClusterRequest) (*RestoreVClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreVCluster not implemented")
}
func (UnimplementedVClusterServiceServer) GetVClusterKubeconfig(context.Context, *GetVClusterKubeconfigRequest) (*GetVClusterKubeconfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVClusterKubeconfig not implemented")
}
func (UnimplementedVClusterServiceServer) WatchVCluster(*WatchVClusterRequest, grpc.ServerStreamingServer[WatchVClusterResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchVCluster not implemented")
}
func (UnimplementedVClusterServiceServer) mustEmbedUnimplementedVClusterServiceServer() {}
func (UnimplementedVClusterServiceServer) testEmbeddedByValue()                         {}

// UnsafeVClusterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VClusterServiceServer will
// result in compilation errors.
type UnsafeVClusterServiceServer interface {
	mustEmbedUnimplementedVClusterServiceServer()
}

func RegisterVClusterServiceServer(s grpc.ServiceRegistrar, srv VClusterServiceServer) {
	// If the following call panics, it indicates UnimplementedVClusterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VClusterService_ServiceDesc, srv)
}

func _VClusterService_CreateVCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VClusterServiceServer).CreateVCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VClusterService_CreateVCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VClusterServiceServer).CreateVCluster(ctx, req.(*CreateVClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VClusterService_GetVCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VClusterServiceServer).GetVCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VClusterService_GetVCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VClusterServiceServer).GetVCluster(ctx, req.(*GetVClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VClusterService_ListVClusters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVClustersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VClusterServiceServer).ListVClusters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VClusterService_ListVClusters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VClusterServiceServer).ListVClusters(ctx, req.(*ListVClustersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VClusterService_UpdateVCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VClusterServiceServer).UpdateVCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VClusterService_UpdateVCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VClusterServiceServer).UpdateVCluster(ctx, req.(*UpdateVClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VClusterService_DeleteVCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VClusterServiceServer).DeleteVCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VClusterService_DeleteVCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VClusterServiceServer).DeleteVCluster(ctx, req.(*DeleteVClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VClusterService_ScaleVCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScaleVClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VClusterServiceServer).ScaleVCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VClusterService_ScaleVCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VClusterServiceServer).ScaleVCluster(ctx, req.(*ScaleVClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VClusterService_SuspendVCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendVClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VClusterServiceServer).SuspendVCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VClusterService_SuspendVCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VClusterServiceServer).SuspendVCluster(ctx, req.(*SuspendVClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VClusterService_ResumeVCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeVClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VClusterServiceServer).ResumeVCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VClusterService_ResumeVCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VClusterServiceServer).ResumeVCluster(ctx, req.(*ResumeVClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VClusterService_SnapshotVCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotVClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VClusterServiceServer).SnapshotVCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VClusterService_SnapshotVCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VClusterServiceServer).SnapshotVCluster(ctx, req.(*SnapshotVClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VClusterService_RestoreVCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreVClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VClusterServiceServer).RestoreVCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VClusterService_RestoreVCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VClusterServiceServer).RestoreVCluster(ctx, req.(*RestoreVClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VClusterService_GetVClusterKubeconfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVClusterKubeconfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VClusterServiceServer).GetVClusterKubeconfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VClusterService_GetVClusterKubeconfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VClusterServiceServer).GetVClusterKubeconfig(ctx, req.(*GetVClusterKubeconfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VClusterService_WatchVCluster_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchVClusterRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VClusterServiceServer).WatchVCluster(m, &grpc.GenericServerStream[WatchVClusterRequest, WatchVClusterResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VClusterService_WatchVClusterServer = grpc.ServerStreamingServer[WatchVClusterResponse]

// VClusterService_ServiceDesc is the grpc.ServiceDesc for VClusterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VClusterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vcluster.api.v1.VClusterService",
	HandlerType: (*VClusterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVCluster",
			Handler:    _VClusterService_CreateVCluster_Handler,
		},
		{
			MethodName: "GetVCluster",
			Handler:    _VClusterService_GetVCluster_Handler,
		},
		{
			MethodName: "ListVClusters",
			Handler:    _VClusterService_ListVClusters_Handler,
		},
		{
			MethodName: "UpdateVCluster",
			Handler:    _VClusterService_UpdateVCluster_Handler,
		},
		{
			MethodName: "DeleteVCluster",
			Handler:    _VClusterService_DeleteVCluster_Handler,
		},
		{
			MethodName: "ScaleVCluster",
			Handler:    _VClusterService_ScaleVCluster_Handler,
		},
		{
			MethodName: "SuspendVCluster",
			Handler:    _VClusterService_SuspendVCluster_Handler,
		},
		{
			MethodName: "ResumeVCluster",
			Handler:    _VClusterService_ResumeVCluster_Handler,
		},
		{
			MethodName: "SnapshotVCluster",
			Handler:    _VClusterService_SnapshotVCluster_Handler,
		},
		{
			MethodName: "RestoreVCluster",
			Handler:    _VClusterService_RestoreVCluster_Handler,
		},
		{
			MethodName: "GetVClusterKubeconfig",
			Handler:    _VClusterService_GetVClusterKubeconfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchVCluster",
			Handler:       _VClusterService_WatchVCluster_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vcluster/api/v1/vcluster_api.proto",
}

const (
	SnapshotService_ListSnapshots_FullMethodName  = "/vcluster.api.v1.SnapshotService/ListSnapshots"
	SnapshotService_GetSnapshot_FullMethodName    = "/vcluster.api.v1.SnapshotService/GetSnapshot"
	SnapshotService_DeleteSnapshot_FullMethodName = "/vcluster.api.v1.SnapshotService/DeleteSnapshot"
)

// SnapshotServiceClient is the client API for SnapshotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SnapshotService provides APIs for managing vcluster snapshots.
type SnapshotServiceClient interface {
	// ListSnapshots lists all snapshots for a vcluster.
	ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error)
	// GetSnapshot retrieves a specific snapshot.
	GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error)
	// DeleteSnapshot deletes a snapshot.
	DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error)
}

type snapshotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSnapshotServiceClient(cc grpc.ClientConnInterface) SnapshotServiceClient {
	return &snapshotServiceClient{cc}
}

func (c *snapshotServiceClient) ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnapshotsResponse)
	err := c.cc.Invoke(ctx, SnapshotService_ListSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotServiceClient) GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSnapshotResponse)
	err := c.cc.Invoke(ctx, SnapshotService_GetSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotServiceClient) DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSnapshotResponse)
	err := c.cc.Invoke(ctx, SnapshotService_DeleteSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnapshotServiceServer is the server API for SnapshotService service.
// All implementations must embed UnimplementedSnapshotServiceServer
// for forward compatibility.
//
// SnapshotService provides APIs for managing vcluster snapshots.
type SnapshotServiceServer interface {
	// ListSnapshots lists all snapshots for a vcluster.
	ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error)
	// GetSnapshot retrieves a specific snapshot.
	GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error)
	// DeleteSnapshot deletes a snapshot.
	DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error)
	mustEmbedUnimplementedSnapshotServiceServer()
}

// UnimplementedSnapshotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSnapshotServiceServer struct{}

func (UnimplementedSnapshotServiceServer) ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (UnimplementedSnapshotServiceServer) GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedSnapshotServiceServer) DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSnapshot not implemented")
}
func (UnimplementedSnapshotServiceServer) mustEmbedUnimplementedSnapshotServiceServer() {}
func (UnimplementedSnapshotServiceServer) testEmbeddedByValue()                         {}

// UnsafeSnapshotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnapshotServiceServer will
// result in compilation errors.
type UnsafeSnapshotServiceServer interface {
	mustEmbedUnimplementedSnapshotServiceServer()
}

func RegisterSnapshotServiceServer(s grpc.ServiceRegistrar, srv SnapshotServiceServer) {
	// If the following call panics, it indicates UnimplementedSnapshotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SnapshotService_ServiceDesc, srv)
}

func _SnapshotService_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotServiceServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotService_ListSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotServiceServer).ListSnapshots(ctx, req.(*ListSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotService_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotServiceServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotService_GetSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotServiceServer).GetSnapshot(ctx, req.(*GetSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotService_DeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotServiceServer).DeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotService_DeleteSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotServiceServer).DeleteSnapshot(ctx, req.(*DeleteSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SnapshotService_ServiceDesc is the grpc.ServiceDesc for SnapshotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnapshotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vcluster.api.v1.SnapshotService",
	HandlerType: (*SnapshotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSnapshots",
			Handler:    _SnapshotService_ListSnapshots_Handler,
		},
		{
			MethodName: "GetSnapshot",
			Handler:    _SnapshotService_GetSnapshot_Handler,
		},
		{
			MethodName: "DeleteSnapshot",
			Handler:    _SnapshotService_DeleteSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vcluster/api/v1/vcluster_api.proto",
}
