# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from vcluster.api.v1 import vcluster_api_pb2 as vcluster_dot_api_dot_v1_dot_vcluster__api__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vcluster/api/v1/vcluster_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VClusterServiceStub(object):
    """============================================================================
    VClusterService - 虚拟集群管理服务
    ============================================================================

    VClusterService provides VM-like APIs for managing virtual Kubernetes clusters.
    This service abstracts vcluster operations into familiar IaaS-style semantics
    while preserving vcluster's cloud-native characteristics.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateVCluster = channel.unary_unary(
                '/vcluster.api.v1.VClusterService/CreateVCluster',
                request_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.CreateVClusterRequest.SerializeToString,
                response_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.CreateVClusterResponse.FromString,
                _registered_method=True)
        self.GetVCluster = channel.unary_unary(
                '/vcluster.api.v1.VClusterService/GetVCluster',
                request_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.GetVClusterRequest.SerializeToString,
                response_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.GetVClusterResponse.FromString,
                _registered_method=True)
        self.ListVClusters = channel.unary_unary(
                '/vcluster.api.v1.VClusterService/ListVClusters',
                request_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.ListVClustersRequest.SerializeToString,
                response_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.ListVClustersResponse.FromString,
                _registered_method=True)
        self.UpdateVCluster = channel.unary_unary(
                '/vcluster.api.v1.VClusterService/UpdateVCluster',
                request_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.UpdateVClusterRequest.SerializeToString,
                response_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.UpdateVClusterResponse.FromString,
                _registered_method=True)
        self.DeleteVCluster = channel.unary_unary(
                '/vcluster.api.v1.VClusterService/DeleteVCluster',
                request_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.DeleteVClusterRequest.SerializeToString,
                response_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.DeleteVClusterResponse.FromString,
                _registered_method=True)
        self.ScaleVCluster = channel.unary_unary(
                '/vcluster.api.v1.VClusterService/ScaleVCluster',
                request_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.ScaleVClusterRequest.SerializeToString,
                response_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.ScaleVClusterResponse.FromString,
                _registered_method=True)
        self.SuspendVCluster = channel.unary_unary(
                '/vcluster.api.v1.VClusterService/SuspendVCluster',
                request_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.SuspendVClusterRequest.SerializeToString,
                response_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.SuspendVClusterResponse.FromString,
                _registered_method=True)
        self.ResumeVCluster = channel.unary_unary(
                '/vcluster.api.v1.VClusterService/ResumeVCluster',
                request_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.ResumeVClusterRequest.SerializeToString,
                response_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.ResumeVClusterResponse.FromString,
                _registered_method=True)
        self.SnapshotVCluster = channel.unary_unary(
                '/vcluster.api.v1.VClusterService/SnapshotVCluster',
                request_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.SnapshotVClusterRequest.SerializeToString,
                response_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.SnapshotVClusterResponse.FromString,
                _registered_method=True)
        self.RestoreVCluster = channel.unary_unary(
                '/vcluster.api.v1.VClusterService/RestoreVCluster',
                request_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.RestoreVClusterRequest.SerializeToString,
                response_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.RestoreVClusterResponse.FromString,
                _registered_method=True)
        self.GetVClusterKubeconfig = channel.unary_unary(
                '/vcluster.api.v1.VClusterService/GetVClusterKubeconfig',
                request_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.GetVClusterKubeconfigRequest.SerializeToString,
                response_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.GetVClusterKubeconfigResponse.FromString,
                _registered_method=True)
        self.WatchVCluster = channel.unary_stream(
                '/vcluster.api.v1.VClusterService/WatchVCluster',
                request_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.WatchVClusterRequest.SerializeToString,
                response_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.WatchVClusterResponse.FromString,
                _registered_method=True)


class VClusterServiceServicer(object):
    """============================================================================
    VClusterService - 虚拟集群管理服务
    ============================================================================

    VClusterService provides VM-like APIs for managing virtual Kubernetes clusters.
    This service abstracts vcluster operations into familiar IaaS-style semantics
    while preserving vcluster's cloud-native characteristics.
    """

    def CreateVCluster(self, request, context):
        """CreateVCluster creates a new virtual Kubernetes cluster.
        Similar to VM provisioning, but creates a vcluster control plane.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVCluster(self, request, context):
        """GetVCluster retrieves details of a specific virtual cluster.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVClusters(self, request, context):
        """ListVClusters lists all virtual clusters with pagination support.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVCluster(self, request, context):
        """UpdateVCluster updates an existing virtual cluster's configuration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVCluster(self, request, context):
        """DeleteVCluster deletes a virtual cluster and all its resources.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScaleVCluster(self, request, context):
        """ScaleVCluster adjusts the resource allocation of a virtual cluster.
        Similar to VM resizing, but modifies resource quotas and control-plane specs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuspendVCluster(self, request, context):
        """SuspendVCluster suspends a running virtual cluster.
        Unlike VM power-off, this scales down control-plane pods and optionally drains workloads.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeVCluster(self, request, context):
        """ResumeVCluster resumes a suspended virtual cluster.
        Restores control-plane pods and reconciles workload state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SnapshotVCluster(self, request, context):
        """SnapshotVCluster creates a point-in-time snapshot of a virtual cluster.
        Captures etcd state and metadata, not disk images like VM snapshots.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreVCluster(self, request, context):
        """RestoreVCluster restores a virtual cluster from a snapshot.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVClusterKubeconfig(self, request, context):
        """GetVClusterKubeconfig retrieves the kubeconfig for accessing a virtual cluster.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchVCluster(self, request, context):
        """WatchVCluster streams real-time updates for a virtual cluster.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VClusterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateVCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVCluster,
                    request_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.CreateVClusterRequest.FromString,
                    response_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.CreateVClusterResponse.SerializeToString,
            ),
            'GetVCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVCluster,
                    request_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.GetVClusterRequest.FromString,
                    response_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.GetVClusterResponse.SerializeToString,
            ),
            'ListVClusters': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVClusters,
                    request_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.ListVClustersRequest.FromString,
                    response_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.ListVClustersResponse.SerializeToString,
            ),
            'UpdateVCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVCluster,
                    request_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.UpdateVClusterRequest.FromString,
                    response_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.UpdateVClusterResponse.SerializeToString,
            ),
            'DeleteVCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVCluster,
                    request_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.DeleteVClusterRequest.FromString,
                    response_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.DeleteVClusterResponse.SerializeToString,
            ),
            'ScaleVCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.ScaleVCluster,
                    request_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.ScaleVClusterRequest.FromString,
                    response_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.ScaleVClusterResponse.SerializeToString,
            ),
            'SuspendVCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.SuspendVCluster,
                    request_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.SuspendVClusterRequest.FromString,
                    response_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.SuspendVClusterResponse.SerializeToString,
            ),
            'ResumeVCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeVCluster,
                    request_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.ResumeVClusterRequest.FromString,
                    response_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.ResumeVClusterResponse.SerializeToString,
            ),
            'SnapshotVCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.SnapshotVCluster,
                    request_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.SnapshotVClusterRequest.FromString,
                    response_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.SnapshotVClusterResponse.SerializeToString,
            ),
            'RestoreVCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreVCluster,
                    request_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.RestoreVClusterRequest.FromString,
                    response_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.RestoreVClusterResponse.SerializeToString,
            ),
            'GetVClusterKubeconfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVClusterKubeconfig,
                    request_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.GetVClusterKubeconfigRequest.FromString,
                    response_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.GetVClusterKubeconfigResponse.SerializeToString,
            ),
            'WatchVCluster': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchVCluster,
                    request_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.WatchVClusterRequest.FromString,
                    response_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.WatchVClusterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vcluster.api.v1.VClusterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vcluster.api.v1.VClusterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VClusterService(object):
    """============================================================================
    VClusterService - 虚拟集群管理服务
    ============================================================================

    VClusterService provides VM-like APIs for managing virtual Kubernetes clusters.
    This service abstracts vcluster operations into familiar IaaS-style semantics
    while preserving vcluster's cloud-native characteristics.
    """

    @staticmethod
    def CreateVCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vcluster.api.v1.VClusterService/CreateVCluster',
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.CreateVClusterRequest.SerializeToString,
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.CreateVClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vcluster.api.v1.VClusterService/GetVCluster',
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.GetVClusterRequest.SerializeToString,
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.GetVClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVClusters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vcluster.api.v1.VClusterService/ListVClusters',
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.ListVClustersRequest.SerializeToString,
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.ListVClustersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateVCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vcluster.api.v1.VClusterService/UpdateVCluster',
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.UpdateVClusterRequest.SerializeToString,
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.UpdateVClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vcluster.api.v1.VClusterService/DeleteVCluster',
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.DeleteVClusterRequest.SerializeToString,
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.DeleteVClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScaleVCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vcluster.api.v1.VClusterService/ScaleVCluster',
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.ScaleVClusterRequest.SerializeToString,
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.ScaleVClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuspendVCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vcluster.api.v1.VClusterService/SuspendVCluster',
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.SuspendVClusterRequest.SerializeToString,
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.SuspendVClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeVCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vcluster.api.v1.VClusterService/ResumeVCluster',
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.ResumeVClusterRequest.SerializeToString,
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.ResumeVClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SnapshotVCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vcluster.api.v1.VClusterService/SnapshotVCluster',
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.SnapshotVClusterRequest.SerializeToString,
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.SnapshotVClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreVCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vcluster.api.v1.VClusterService/RestoreVCluster',
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.RestoreVClusterRequest.SerializeToString,
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.RestoreVClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVClusterKubeconfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vcluster.api.v1.VClusterService/GetVClusterKubeconfig',
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.GetVClusterKubeconfigRequest.SerializeToString,
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.GetVClusterKubeconfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchVCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vcluster.api.v1.VClusterService/WatchVCluster',
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.WatchVClusterRequest.SerializeToString,
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.WatchVClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SnapshotServiceStub(object):
    """============================================================================
    Snapshot Service Messages
    ============================================================================

    SnapshotService provides APIs for managing vcluster snapshots.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSnapshots = channel.unary_unary(
                '/vcluster.api.v1.SnapshotService/ListSnapshots',
                request_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.ListSnapshotsRequest.SerializeToString,
                response_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.ListSnapshotsResponse.FromString,
                _registered_method=True)
        self.GetSnapshot = channel.unary_unary(
                '/vcluster.api.v1.SnapshotService/GetSnapshot',
                request_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.GetSnapshotRequest.SerializeToString,
                response_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.GetSnapshotResponse.FromString,
                _registered_method=True)
        self.DeleteSnapshot = channel.unary_unary(
                '/vcluster.api.v1.SnapshotService/DeleteSnapshot',
                request_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.DeleteSnapshotRequest.SerializeToString,
                response_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.DeleteSnapshotResponse.FromString,
                _registered_method=True)


class SnapshotServiceServicer(object):
    """============================================================================
    Snapshot Service Messages
    ============================================================================

    SnapshotService provides APIs for managing vcluster snapshots.
    """

    def ListSnapshots(self, request, context):
        """ListSnapshots lists all snapshots for a vcluster.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSnapshot(self, request, context):
        """GetSnapshot retrieves a specific snapshot.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSnapshot(self, request, context):
        """DeleteSnapshot deletes a snapshot.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SnapshotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSnapshots': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSnapshots,
                    request_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.ListSnapshotsRequest.FromString,
                    response_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.ListSnapshotsResponse.SerializeToString,
            ),
            'GetSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSnapshot,
                    request_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.GetSnapshotRequest.FromString,
                    response_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.GetSnapshotResponse.SerializeToString,
            ),
            'DeleteSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSnapshot,
                    request_deserializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.DeleteSnapshotRequest.FromString,
                    response_serializer=vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.DeleteSnapshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vcluster.api.v1.SnapshotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vcluster.api.v1.SnapshotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SnapshotService(object):
    """============================================================================
    Snapshot Service Messages
    ============================================================================

    SnapshotService provides APIs for managing vcluster snapshots.
    """

    @staticmethod
    def ListSnapshots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vcluster.api.v1.SnapshotService/ListSnapshots',
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.ListSnapshotsRequest.SerializeToString,
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.ListSnapshotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vcluster.api.v1.SnapshotService/GetSnapshot',
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.GetSnapshotRequest.SerializeToString,
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.GetSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vcluster.api.v1.SnapshotService/DeleteSnapshot',
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.DeleteSnapshotRequest.SerializeToString,
            vcluster_dot_api_dot_v1_dot_vcluster__api__pb2.DeleteSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
